version: "3.2"
services:
  oe-application:
    image: openemis/core:3.27.0
    depends_on:
      - oe-database
    ports:
      - "8082:80"
    environment:
      - MYSQL_HOST=oe-database
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=demo
      - MYSQL_DB=openemis_core
  oe-database:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=demo 
      - MYSQL_DATABASE=openemis_core
    volumes: 
      - oe-data:/var/lib/mysql
      - ./config/sql/openemis-core-3-27-0.sql:/docker-entrypoint-initdb.d/openemis-core-3-27-0.sql
    command: mysqld --sql_mode="STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
  oe-admin:
    image: phpmyadmin/phpmyadmin:4.7
    depends_on:
      - oe-database
    ports:
      - "8083:80"
    environment:
      - PMA_HOST=oe-database
      - PMA_PORT=3306
volumes: 
  oe-data:
    driver: local
